name: Typescript type checking

on:
  push:
    branches:
    - '**'
  pull_request:
    branches-ignore:
    - main
  workflow_dispatch:

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: actions/cache@v1
        id: cache-dependencies
        with:
          path: '.'
          key: ${{ github.sha }}
  type_checking:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/cache@v1
        id: restore-dependencies
        with:
          path: '.'
          key: ${{ github.sha }}
      - name: Run type checking
        run: npm run ts
